version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
    networks:
      - webnet

networks:
  webnet:
    external: true


  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #   depends_on:
  #     - app
  #   restart: unless-stopped

  # code-server:
  #   image: codercom/code-server:latest
  #   user: "1001:1002"  # Reemplaza con tu UID y GID reales
  #   container_name: code-server
  #   environment:
  #     - PASSWORD=ML!gsx90l02  # Establece la contraseña para code-server
  #   volumes:
  #     - "/var/www/webapp:/home/coder/projectos"  # A
  #   ports:
  #     - "8443:8080"  # Expone el puerto 8443 del host al puerto 8080 del contenedor

