version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    ports:  # Cambia 'expose' por 'ports' para hacer el puerto accesible fuera de Docker.
      - "4321:4321"
    environment:
      - NODE_ENV=production
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    restart: unless-stopped
