version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    ports:  # Cambia 'expose' por 'ports' para hacer el puerto accesible fuera de Docker.
      - "4321:4321"
    environment:
        - HOST=0.0.0.0
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "8444:443" # Puerto personalizado HTTPS para code.datqbox.com
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    restart: unless-stopped
